platform :ios, '5.1'
pod 'ViewDeck'
pod 'PSCollectionView'
pod 'WCAlertView'
pod 'GDataXML-HTML'
pod 'ISRefreshControl', '~> 1.4.1'
pod 'SVProgressHUD'
pod 'AFNetworking'
pod 'QuickDialog'
pod 'SMPageControl'
